insert into flights values('AA01','AIRASIA','DELHI','MUMBAI',4000);
insert into flights values('AA02','AIRASIA','DELHI','BENGALURU',4500);
insert into flights values('AA03','AIRASIA','DELHI','HYDERABAD',4500);
insert into flights values('AA04','AIRASIA','DELHI','CHENNAI',5000);
insert into flights values('AA05','AIRASIA','DELHI','KOLKATA',3500);
insert into flights values('AA06','AIRASIA','DELHI','BHUBANESHWAR',4000);
insert into flights values('AA07','AIRASIA','DELHI','AHMEDABAD',2000);
insert into flights values('AA08','AIRASIA','DELHI','GUWAHATI',4000);
insert into flights values('AA09','AIRASIA','MUMBAI','DELHI',4000);
insert into flights values('AA10','AIRASIA','MUMBAI','BENGALURU',2500);
insert into flights values('AA11','AIRASIA','MUMBAI','HYDERABAD',3000);
insert into flights values('AA12','AIRASIA','MUMBAI','CHENNAI',4000);
insert into flights values('AA13','AIRASIA','MUMBAI','KOLKATA',4000);
insert into flights values('AA14','AIRASIA','MUMBAI','BHUBANESHWAR',3500);
insert into flights values('AA15','AIRASIA','MUMBAI','AHMEDABAD',3500);
insert into flights values('AA16','AIRASIA','MUMBAI','GUWAHATI',5000);
insert into flights values('AA17','AIRASIA','BENGALURU','DELHI',4500);
insert into flights values('AA18','AIRASIA','BENGALURU','MUMBAI',2500);
insert into flights values('AA19','AIRASIA','BENGALURU','HYDERABAD',2500);
insert into flights values('AA20','AIRASIA','BENGALURU','CHENNAI',3000);
insert into flights values('AA21','AIRASIA','BENGALURU','KOLKATA',3500);
insert into flights values('AA22','AIRASIA','BENGALURU','BHUBANESHWAR',3000);
insert into flights values('AA23','AIRASIA','BENGALURU','AHMEDABAD',3500);
insert into flights values('AA24','AIRASIA','BENGALURU','GUWAHATI',5000);
insert into flights values('AA25','AIRASIA','HYDERABAD','DELHI',4500);
insert into flights values('AA26','AIRASIA','HYDERABAD','MUMBAI',3000);
insert into flights values('AA27','AIRASIA','HYDERABAD','BENGALURU',2500);
insert into flights values('AA28','AIRASIA','HYDERABAD','CHENNAI',3000);
insert into flights values('AA29','AIRASIA','HYDERABAD','KOLKATA',3500);
insert into flights values('AA30','AIRASIA','HYDERABAD','BHUBANESHWAR',2000);
insert into flights values('AA31','AIRASIA','HYDERABAD','AHMEDABAD',3500);
insert into flights values('AA32','AIRASIA','HYDERABAD','GUWAHATI',5000);
insert into flights values('AA33','AIRASIA','CHENNAI','DELHI',5000);
insert into flights values('AA34','AIRASIA','CHENNAI','MUMBAI',4000);
insert into flights values('AA35','AIRASIA','CHENNAI','BENGALURU',3000);
insert into flights values('AA36','AIRASIA','CHENNAI','HYDERABAD',3000);
insert into flights values('AA37','AIRASIA','CHENNAI','KOLKATA',4000);
insert into flights values('AA38','AIRASIA','CHENNAI','BHUBANESHWAR',3000);
insert into flights values('AA39','AIRASIA','CHENNAI','AHMEDABAD',4500);
insert into flights values('AA40','AIRASIA','CHENNAI','GUWAHATI',5500);
insert into flights values('AA41','AIRASIA','KOLKATA','DELHI',3500);
insert into flights values('AA42','AIRASIA','KOLKATA','MUMBAI',4000);
insert into flights values('AA43','AIRASIA','KOLKATA','BENGALURU',3500);
insert into flights values('AA44','AIRASIA','KOLKATA','HYDERABAD',3500);
insert into flights values('AA45','AIRASIA','KOLKATA','CHENNAI',4000);
insert into flights values('AA46','AIRASIA','KOLKATA','BHUBANESHWAR',2500);
insert into flights values('AA47','AIRASIA','KOLKATA','AHMEDABAD',3500);
insert into flights values('AA48','AIRASIA','KOLKATA','GUWAHATI',3000);
insert into flights values('AA49','AIRASIA','BHUBANESHWAR','DELHI',4000);
insert into flights values('AA50','AIRASIA','BHUBANESHWAR','MUMBAI',3500);
insert into flights values('AA51','AIRASIA','BHUBANESHWAR','BENGALURU',3000);
insert into flights values('AA52','AIRASIA','BHUBANESHWAR','HYDERABAD',2000);
insert into flights values('AA53','AIRASIA','BHUBANESHWAR','CHENNAI',3000);
insert into flights values('AA54','AIRASIA','BHUBANESHWAR','KOLKATA',2500);
insert into flights values('AA55','AIRASIA','AHMEDABAD','DELHI',2000);
insert into flights values('AA56','AIRASIA','AHMEDABAD','MUMBAI',3500);
insert into flights values('AA57','AIRASIA','AHMEDABAD','BENGALURU',3500);
insert into flights values('AA58','AIRASIA','AHMEDABAD','HYDERABAD',3500);
insert into flights values('AA59','AIRASIA','AHMEDABAD','CHENNAI',4500);
insert into flights values('AA60','AIRASIA','AHMEDABAD','KOLKATA',3500);
insert into flights values('AA61','AIRASIA','GUWAHATI','DELHI',4000);
insert into flights values('AA62','AIRASIA','GUWAHATI','MUMBAI',5000);
insert into flights values('AA63','AIRASIA','GUWAHATI','BENGALURU',5000);
insert into flights values('AA64','AIRASIA','GUWAHATI','HYDERABAD',5000);
insert into flights values('AA65','AIRASIA','GUWAHATI','CHENNAI',5500);
insert into flights values('AA66','AIRASIA','GUWAHATI','KOLKATA',3000);
insert into flights values('I01','INDIGO','DELHI','MUMBAI',3800);
insert into flights values('I02','INDIGO','DELHI','BENGALURU',4300);
insert into flights values('I03','INDIGO','DELHI','HYDERABAD',4300);
insert into flights values('I04','INDIGO','DELHI','CHENNAI',4800);
insert into flights values('I05','INDIGO','DELHI','KOLKATA',3300);
insert into flights values('I06','INDIGO','DELHI','BHUBANESHWAR',4000);
insert into flights values('I07','INDIGO','DELHI','THIRUVANANTHAPURAM',5000);
insert into flights values('I08','INDIGO','DELHI','VISHAKAPATNAM',4500);
insert into flights values('I09','INDIGO','MUMBAI','DELHI',3800);
insert into flights values('I10','INDIGO','MUMBAI','BENGALURU',2300);
insert into flights values('I11','INDIGO','MUMBAI','HYDERABAD',2800);
insert into flights values('I12','INDIGO','MUMBAI','CHENNAI',3800);
insert into flights values('I13','INDIGO','MUMBAI','KOLKATA',3800);
insert into flights values('I14','INDIGO','MUMBAI','BHUBANESHWAR',3500);
insert into flights values('I15','INDIGO','MUMBAI','THIRUVANANTHAPURAM',4000);
insert into flights values('I16','INDIGO','MUMBAI','VISHAKAPATNAM',4000);
insert into flights values('I17','INDIGO','BENGALURU','DELHI',4300);
insert into flights values('I18','INDIGO','BENGALURU','MUMBAI',2300);
insert into flights values('I19','INDIGO','BENGALURU','HYDERABAD',2300);
insert into flights values('I20','INDIGO','BENGALURU','CHENNAI',2800);
insert into flights values('I21','INDIGO','BENGALURU','KOLKATA',3300);
insert into flights values('I22','INDIGO','BENGALURU','BHUBANESHWAR',3000);
insert into flights values('I23','INDIGO','BENGALURU','THIRUVANANTHAPURAM',3500);
insert into flights values('I24','INDIGO','BENGALURU','VISHAKAPATNAM',3500);
insert into flights values('I25','INDIGO','HYDERABAD','DELHI',4300);
insert into flights values('I26','INDIGO','HYDERABAD','MUMBAI',2800);
insert into flights values('I27','INDIGO','HYDERABAD','BENGALURU',2300);
insert into flights values('I28','INDIGO','HYDERABAD','CHENNAI',2800);
insert into flights values('I29','INDIGO','HYDERABAD','KOLKATA',3300);
insert into flights values('I30','INDIGO','HYDERABAD','BHUBANESHWAR',2000);
insert into flights values('I31','INDIGO','HYDERABAD','THIRUVANANTHAPURAM',3500);
insert into flights values('I32','INDIGO','HYDERABAD','VISHAKAPATNAM',2500);
insert into flights values('I33','INDIGO','CHENNAI','DELHI',4800);
insert into flights values('I34','INDIGO','CHENNAI','MUMBAI',3800);
insert into flights values('I35','INDIGO','CHENNAI','BENGALURU',2800);
insert into flights values('I36','INDIGO','CHENNAI','HYDERABAD',2800);
insert into flights values('I37','INDIGO','CHENNAI','KOLKATA',3800);
insert into flights values('I38','INDIGO','CHENNAI','BHUBANESHWAR',3000);
insert into flights values('I39','INDIGO','CHENNAI','THIRUVANANTHAPURAM',3000);
insert into flights values('I40','INDIGO','CHENNAI','VISHAKAPATNAM',3000);
insert into flights values('I41','INDIGO','KOLKATA','DELHI',3300);
insert into flights values('I42','INDIGO','KOLKATA','MUMBAI',3800);
insert into flights values('I43','INDIGO','KOLKATA','BENGALURU',3300);
insert into flights values('I44','INDIGO','KOLKATA','HYDERABAD',3300);
insert into flights values('I45','INDIGO','KOLKATA','CHENNAI',3800);
insert into flights values('I46','INDIGO','KOLKATA','BHUBANESHWAR',4500);
insert into flights values('I47','INDIGO','KOLKATA','THIRUVANANTHAPURAM',4500);
insert into flights values('I48','INDIGO','KOLKATA','VISHAKAPATNAM',3500);
insert into flights values('I49','INDIGO','BHUBANESHWAR','DELHI',4000);
insert into flights values('I50','INDIGO','BHUBANESHWAR','MUMBAI',3500);
insert into flights values('I51','INDIGO','BHUBANESHWAR','BENGALURU',3000);
insert into flights values('I52','INDIGO','BHUBANESHWAR','HYDERABAD',2000);
insert into flights values('I53','INDIGO','BHUBANESHWAR','CHENNAI',3000);
insert into flights values('I54','INDIGO','BHUBANESHWAR','KOLKATA',2500);
insert into flights values('I55','INDIGO','THIRUVANANTHAPURAM','DELHI',5000);
insert into flights values('I56','INDIGO','THIRUVANANTHAPURAM','MUMBAI',4000);
insert into flights values('I57','INDIGO','THIRUVANANTHAPURAM','BENGALURU',3500);
insert into flights values('I58','INDIGO','THIRUVANANTHAPURAM','HYDERABAD',3500);
insert into flights values('I59','INDIGO','THIRUVANANTHAPURAM','CHENNAI',3000);
insert into flights values('I60','INDIGO','THIRUVANANTHAPURAM','KOLKATA',4500);
insert into flights values('I61','INDIGO','VISHAKAPATNAM','DELHI',4500);
insert into flights values('I62','INDIGO','VISHAKAPATNAM','MUMBAI',4000);
insert into flights values('I63','INDIGO','VISHAKAPATNAM','BENGALURU',3500);
insert into flights values('I64','INDIGO','VISHAKAPATNAM','HYDERABAD',2500);
insert into flights values('I65','INDIGO','VISHAKAPATNAM','CHENNAI',3000);
insert into flights values('I66','INDIGO','VISHAKAPATNAM','KOLKATA',3500);
insert into flights values('SJ01','SPICEJET','DELHI','MUMBAI',3700);
insert into flights values('SJ02','SPICEJET','DELHI','BENGALURU',3200);
insert into flights values('SJ03','SPICEJET','DELHI','HYDERABAD',3200);
insert into flights values('SJ04','SPICEJET','DELHI','CHENNAI',4700);
insert into flights values('SJ05','SPICEJET','DELHI','KOLKATA',3200);
insert into flights values('SJ06','SPICEJET','DELHI','LUCKNOW',2000);
insert into flights values('SJ07','SPICEJET','DELHI','THIRUVANANTHAPURAM',5000);
insert into flights values('SJ08','SPICEJET','DELHI','VISHAKAPATNAM',4500);
insert into flights values('SJ09','SPICEJET','MUMBAI','DELHI',3700);
insert into flights values('SJ10','SPICEJET','MUMBAI','BENGALURU',2200);
insert into flights values('SJ11','SPICEJET','MUMBAI','HYDERABAD',2700);
insert into flights values('SJ12','SPICEJET','MUMBAI','CHENNAI',3700);
insert into flights values('SJ13','SPICEJET','MUMBAI','KOLKATA',3700);
insert into flights values('SJ14','SPICEJET','MUMBAI','LUCKNOW',3000);
insert into flights values('SJ15','SPICEJET','MUMBAI','THIRUVANANTHAPURAM',4000);
insert into flights values('SJ16','SPICEJET','MUMBAI','VISHAKAPATNAM',4000);
insert into flights values('SJ17','SPICEJET','BENGALURU','DELHI',4200);
insert into flights values('SJ18','SPICEJET','BENGALURU','MUMBAI',2200);
insert into flights values('SJ19','SPICEJET','BENGALURU','HYDERABAD',2200);
insert into flights values('SJ20','SPICEJET','BENGALURU','CHENNAI',2700);
insert into flights values('SJ21','SPICEJET','BENGALURU','KOLKATA',3200);
insert into flights values('SJ22','SPICEJET','BENGALURU','LUCKNOW',3500);
insert into flights values('SJ23','SPICEJET','BENGALURU','THIRUVANANTHAPURAM',3500);
insert into flights values('SJ24','SPICEJET','BENGALURU','VISHAKAPATNAM',3500);
insert into flights values('SJ25','SPICEJET','HYDERABAD','DELHI',4200);
insert into flights values('SJ26','SPICEJET','HYDERABAD','MUMBAI',2700);
insert into flights values('SJ27','SPICEJET','HYDERABAD','BENGALURU',2200);
insert into flights values('SJ28','SPICEJET','HYDERABAD','CHENNAI',2700);
insert into flights values('SJ29','SPICEJET','HYDERABAD','KOLKATA',3200);
insert into flights values('SJ30','SPICEJET','HYDERABAD','LUCKNOW',3500);
insert into flights values('SJ31','SPICEJET','HYDERABAD','THIRUVANANTHAPURAM',3500);
insert into flights values('SJ32','SPICEJET','HYDERABAD','VISHAKAPATNAM',2500);
insert into flights values('SJ33','SPICEJET','CHENNAI','DELHI',4700);
insert into flights values('SJ34','SPICEJET','CHENNAI','MUMBAI',3700);
insert into flights values('SJ35','SPICEJET','CHENNAI','BENGALURU',2700);
insert into flights values('SJ36','SPICEJET','CHENNAI','HYDERABAD',2700);
insert into flights values('SJ37','SPICEJET','CHENNAI','KOLKATA',3700);
insert into flights values('SJ38','SPICEJET','CHENNAI','LUCKNOW',4000);
insert into flights values('SJ39','SPICEJET','CHENNAI','THIRUVANANTHAPURAM',3000);
insert into flights values('SJ40','SPICEJET','CHENNAI','VISHAKAPATNAM',3000);
insert into flights values('SJ41','SPICEJET','KOLKATA','DELHI',3200);
insert into flights values('SJ42','SPICEJET','KOLKATA','MUMBAI',3700);
insert into flights values('SJ43','SPICEJET','KOLKATA','BENGALURU',3200);
insert into flights values('SJ44','SPICEJET','KOLKATA','HYDERABAD',3200);
insert into flights values('SJ45','SPICEJET','KOLKATA','CHENNAI',3700);
insert into flights values('SJ46','SPICEJET','KOLKATA','LUCKNOW',2500);
insert into flights values('SJ47','SPICEJET','KOLKATA','THIRUVANANTHAPURAM',4500);
insert into flights values('SJ48','SPICEJET','KOLKATA','VISHAKAPATNAM',3500);
insert into flights values('SJ49','SPICEJET','LUCKNOW','DELHI',2000);
insert into flights values('SJ50','SPICEJET','LUCKNOW','MUMBAI',3000);
insert into flights values('SJ51','SPICEJET','LUCKNOW','BENGALURU',3500);
insert into flights values('SJ52','SPICEJET','LUCKNOW','HYDERABAD',3500);
insert into flights values('SJ53','SPICEJET','LUCKNOW','CHENNAI',4000);
insert into flights values('SJ54','SPICEJET','LUCKNOW','KOLKATA',2500);
insert into flights values('SJ55','SPICEJET','THIRUVANANTHAPURAM','DELHI',5000);
insert into flights values('SJ56','SPICEJET','THIRUVANANTHAPURAM','MUMBAI',4000);
insert into flights values('SJ57','SPICEJET','THIRUVANANTHAPURAM','BENGALURU',3500);
insert into flights values('SJ58','SPICEJET','THIRUVANANTHAPURAM','HYDERABAD',3500);
insert into flights values('SJ59','SPICEJET','THIRUVANANTHAPURAM','CHENNAI',3000);
insert into flights values('SJ60','SPICEJET','THIRUVANANTHAPURAM','KOLKATA',4500);
insert into flights values('SJ61','SPICEJET','VISHAKAPATNAM','DELHI',4500);
insert into flights values('SJ62','SPICEJET','VISHAKAPATNAM','MUMBAI',4000);
insert into flights values('SJ63','SPICEJET','VISHAKAPATNAM','BENGALURU',3500);
insert into flights values('SJ64','SPICEJET','VISHAKAPATNAM','HYDERABAD',2500);
insert into flights values('SJ65','SPICEJET','VISHAKAPATNAM','CHENNAI',3000);
insert into flights values('SJ66','SPICEJET','VISHAKAPATNAM','KOLKATA',3500);
insert into flights values('V01','VISTARA','DELHI','MUMBAI',3900);
insert into flights values('V02','VISTARA','DELHI','BENGALURU',4400);
insert into flights values('V03','VISTARA','DELHI','HYDERABAD',4400);
insert into flights values('V04','VISTARA','DELHI','CHENNAI',4900);
insert into flights values('V05','VISTARA','DELHI','KOLKATA',3400);
insert into flights values('V06','VISTARA','DELHI','AHMEDABAD',2000);
insert into flights values('V07','VISTARA','DELHI','GUWAHATI',4000);
insert into flights values('V08','VISTARA','DELHI','LUCKNOW',2000);
insert into flights values('V09','VISTARA','MUMBAI','DELHI',3900);
insert into flights values('V10','VISTARA','MUMBAI','BENGALURU',2400);
insert into flights values('V11','VISTARA','MUMBAI','HYDERABAD',2900);
insert into flights values('V12','VISTARA','MUMBAI','CHENNAI',3900);
insert into flights values('V13','VISTARA','MUMBAI','KOLKATA',3900);
insert into flights values('V14','VISTARA','MUMBAI','AHMEDABAD',3500);
insert into flights values('V15','VISTARA','MUMBAI','GUWAHATI',5000);
insert into flights values('V16','VISTARA','MUMBAI','LUCKNOW',3000);
insert into flights values('V17','VISTARA','BENGALURU','DELHI',4400);
insert into flights values('V18','VISTARA','BENGALURU','MUMBAI',2400);
insert into flights values('V19','VISTARA','BENGALURU','HYDERABAD',2400);
insert into flights values('V20','VISTARA','BENGALURU','CHENNAI',2900);
insert into flights values('V21','VISTARA','BENGALURU','KOLKATA',3400);
insert into flights values('V22','VISTARA','BENGALURU','AHMEDABAD',3500);
insert into flights values('V23','VISTARA','BENGALURU','GUWAHATI',5000);
insert into flights values('V24','VISTARA','BENGALURU','LUCKNOW',3500);
insert into flights values('V25','VISTARA','HYDERABAD','DELHI',4400);
insert into flights values('V26','VISTARA','HYDERABAD','MUMBAI',2900);
insert into flights values('V27','VISTARA','HYDERABAD','BENGALURU',2400);
insert into flights values('V28','VISTARA','HYDERABAD','CHENNAI',2900);
insert into flights values('V29','VISTARA','HYDERABAD','KOLKATA',3400);
insert into flights values('V30','VISTARA','HYDERABAD','AHMEDABAD',3500);
insert into flights values('V31','VISTARA','HYDERABAD','GUWAHATI',5000);
insert into flights values('V32','VISTARA','HYDERABAD','LUCKNOW',3500);
insert into flights values('V33','VISTARA','CHENNAI','DELHI',4900);
insert into flights values('V34','VISTARA','CHENNAI','MUMBAI',3900);
insert into flights values('V35','VISTARA','CHENNAI','BENGALURU',2900);
insert into flights values('V36','VISTARA','CHENNAI','HYDERABAD',2900);
insert into flights values('V37','VISTARA','CHENNAI','KOLKATA',3900);
insert into flights values('V38','VISTARA','CHENNAI','AHMEDABAD',4500);
insert into flights values('V39','VISTARA','CHENNAI','GUWAHATI',5500);
insert into flights values('V40','VISTARA','CHENNAI','LUCKNOW',4000);
insert into flights values('V41','VISTARA','KOLKATA','DELHI',3400);
insert into flights values('V42','VISTARA','KOLKATA','MUMBAI',3900);
insert into flights values('V43','VISTARA','KOLKATA','BENGALURU',3400);
insert into flights values('V44','VISTARA','KOLKATA','HYDERABAD',3400);
insert into flights values('V45','VISTARA','KOLKATA','CHENNAI',3900);
insert into flights values('V46','VISTARA','KOLKATA','AHMEDABAD',3500);
insert into flights values('V47','VISTARA','KOLKATA','GUWAHATI',3000);
insert into flights values('V48','VISTARA','KOLKATA','LUCKNOW',2500);
insert into flights values('V49','VISTARA','AHMEDABAD','DELHI',2000);
insert into flights values('V50','VISTARA','AHMEDABAD','MUMBAI',3500);
insert into flights values('V51','VISTARA','AHMEDABAD','BENGALURU',3500);
insert into flights values('V52','VISTARA','AHMEDABAD','HYDERABAD',3500);
insert into flights values('V53','VISTARA','AHMEDABAD','CHENNAI',4500);
insert into flights values('V54','VISTARA','AHMEDABAD','KOLKATA',3500);
insert into flights values('V55','VISTARA','GUWAHATI','DELHI',4000);
insert into flights values('V56','VISTARA','GUWAHATI','MUMBAI',5000);
insert into flights values('V57','VISTARA','GUWAHATI','BENGALURU',5000);
insert into flights values('V58','VISTARA','GUWAHATI','HYDERABAD',5000);
insert into flights values('V59','VISTARA','GUWAHATI','CHENNAI',5500);
insert into flights values('V60','VISTARA','GUWAHATI','KOLKATA',3000);
insert into flights values('V61','VISTARA','LUCKNOW','DELHI',2000);
insert into flights values('V62','VISTARA','LUCKNOW','MUMBAI',3000);
insert into flights values('V63','VISTARA','LUCKNOW','BENGALURU',3500);
insert into flights values('V64','VISTARA','LUCKNOW','HYDERABAD',3500);
insert into flights values('V65','VISTARA','LUCKNOW','CHENNAI',4000);
insert into flights values('V66','VISTARA','LUCKNOW','KOLKATA',2500);


update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA01';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA02';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA03';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='AA04';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA05';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA06';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA07';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='AA08';
update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA09';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA10';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA11';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA12';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA13';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA14';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA15';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='AA16';
update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA17';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA18';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='9:30' where FLIGHT_ID='AA19';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA20';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA21';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA22';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='AA23';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='16:00' where FLIGHT_ID='AA24';
update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA25';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA26';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='9:30' where FLIGHT_ID='AA27';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA28';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA29';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA30';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='AA31';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='16:00' where FLIGHT_ID='AA32';
update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA33';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA34';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='9:30' where FLIGHT_ID='AA35';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA36';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA37';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA38';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='AA39';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='AA40';
update flights set DEPATURE_TIME='7:00',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA41';
update flights set DEPATURE_TIME='7:30',ARRIVAL_TIME='9:30' where FLIGHT_ID='AA42';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA43';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA44';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA45';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA46';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='AA47';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='AA48';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA49';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='11:00' where FLIGHT_ID='AA50';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA51';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='10:30' where FLIGHT_ID='AA52';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA53';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='AA54';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='9:00' where FLIGHT_ID='AA55';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='10:00' where FLIGHT_ID='AA56';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA57';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA58';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='AA59';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='AA60';
update flights set DEPATURE_TIME='8:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='AA61';
update flights set DEPATURE_TIME='8:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='AA62';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='AA63';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='AA64';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='AA65';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='AA66';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='I01';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='I02';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='I03';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='I04';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='I05';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='I06';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='I07';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='I08';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='I09';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:00' where FLIGHT_ID='I10';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='I11';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='I12';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='I13';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='I14';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='I15';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='17:30' where FLIGHT_ID='I16';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='I17';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:00' where FLIGHT_ID='I18';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:30' where FLIGHT_ID='I19';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I20';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='I21';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='I22';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='I23';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='18:00' where FLIGHT_ID='I24';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='I25';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I26';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:30' where FLIGHT_ID='I27';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I28';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='I29';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='I30';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='I31';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='18:00' where FLIGHT_ID='I32';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='I33';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='I34';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:30' where FLIGHT_ID='I35';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I36';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='I37';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='I38';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='I39';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='18:30' where FLIGHT_ID='I40';
update flights set DEPATURE_TIME='9:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='I41';
update flights set DEPATURE_TIME='9:30',ARRIVAL_TIME='11:30' where FLIGHT_ID='I42';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='I43';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I44';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='I45';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='I46';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='I47';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='I48';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='I49';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='I50';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='I51';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='I52';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='I53';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='I54';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='11:00' where FLIGHT_ID='I55';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='I56';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='I57';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='I58';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='I59';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='I60';
update flights set DEPATURE_TIME='10:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='I61';
update flights set DEPATURE_TIME='10:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='I62';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='16:30' where FLIGHT_ID='I63';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='17:00' where FLIGHT_ID='I64';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='18:00' where FLIGHT_ID='I65';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='I66';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ01';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ02';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ03';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='SJ04';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ05';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ06';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ07';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='18:30' where FLIGHT_ID='SJ08';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ09';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ10';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ11';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ12';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ13';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ14';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ15';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='19:30' where FLIGHT_ID='SJ16';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ17';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ18';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='SJ19';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ20';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ21';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ22';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='17:00' where FLIGHT_ID='SJ23';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='20:00' where FLIGHT_ID='SJ24';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ25';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ26';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='SJ27';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ28';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ29';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ30';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='16:30' where FLIGHT_ID='SJ31';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='20:00' where FLIGHT_ID='SJ32';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ33';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ34';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='SJ35';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ36';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ37';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ38';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='17:30' where FLIGHT_ID='SJ39';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='20:30' where FLIGHT_ID='SJ40';
update flights set DEPATURE_TIME='11:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ41';
update flights set DEPATURE_TIME='11:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='SJ42';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ43';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ44';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ45';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ46';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='16:30' where FLIGHT_ID='SJ47';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='17:30' where FLIGHT_ID='SJ48';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ49';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='SJ50';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ51';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='SJ52';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ53';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='SJ54';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='SJ55';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='SJ56';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ57';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ58';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='17:30' where FLIGHT_ID='SJ59';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='17:00' where FLIGHT_ID='SJ60';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='SJ61';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='17:30' where FLIGHT_ID='SJ62';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='18:30' where FLIGHT_ID='SJ63';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='19:00' where FLIGHT_ID='SJ64';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='20:00' where FLIGHT_ID='SJ65';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='17:30' where FLIGHT_ID='SJ66';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='V01';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='V02';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='V03';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='15:30' where FLIGHT_ID='V04';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='V05';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='V06';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='V07';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='17:30' where FLIGHT_ID='V08';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='V09';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='V10';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='V11';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='V12';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='V13';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='V14';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='V15';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='18:30' where FLIGHT_ID='V16';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='V17';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='12:00' where FLIGHT_ID='V18';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='V19';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V20';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='14:30' where FLIGHT_ID='V21';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='V22';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='16:00' where FLIGHT_ID='V23';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='19:00' where FLIGHT_ID='V24';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='V25';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V26';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='V27';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V28';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='V29';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='V30';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='V31';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='19:00' where FLIGHT_ID='V32';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='14:00' where FLIGHT_ID='V33';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='V34';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='12:30' where FLIGHT_ID='V35';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V36';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='V37';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='V38';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='16:30' where FLIGHT_ID='V39';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='19:30' where FLIGHT_ID='V40';
update flights set DEPATURE_TIME='12:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='V41';
update flights set DEPATURE_TIME='12:30',ARRIVAL_TIME='12:30' where FLIGHT_ID='V42';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='V43';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V44';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='V45';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='V46';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='15:30' where FLIGHT_ID='V47';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='V48';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='13:00' where FLIGHT_ID='V49';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='14:00' where FLIGHT_ID='V50';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='13:30' where FLIGHT_ID='V51';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='13:30' where FLIGHT_ID='V52';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='V53';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='14:30' where FLIGHT_ID='V54';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='12:00' where FLIGHT_ID='V55';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='13:00' where FLIGHT_ID='V56';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='V57';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='15:00' where FLIGHT_ID='V58';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='16:30' where FLIGHT_ID='V59';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='16:00' where FLIGHT_ID='V60';
update flights set DEPATURE_TIME='13:00',ARRIVAL_TIME='15:00' where FLIGHT_ID='V61';
update flights set DEPATURE_TIME='13:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='V62';
update flights set DEPATURE_TIME='14:00',ARRIVAL_TIME='17:30' where FLIGHT_ID='V63';
update flights set DEPATURE_TIME='14:30',ARRIVAL_TIME='18:00' where FLIGHT_ID='V64';
update flights set DEPATURE_TIME='15:00',ARRIVAL_TIME='19:00' where FLIGHT_ID='V65';
update flights set DEPATURE_TIME='15:30',ARRIVAL_TIME='16:30' where FLIGHT_ID='V66';



